spring:
  rabbitmq:
    host: ${rabbitmq_ip:localhost}
    port: ${rabbitmq_port:5672}
    username: ${rabbitmq_username:guest}
    password: ${rabbitmq_password:guest}

    listener:
      direct:
        default-requeue-rejected: true
      simple:
        default-requeue-rejected: true

  jackson:
    default-property-inclusion: NON_NULL
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
    serialization.INDENT_OUTPUT: false
    serialization:
      write-dates-as-timestamps: true
